### PR TITLE
[test only] Improve `filesIn` test-helper function

### PR DESCRIPTION
**Pull request by d-ronnqvist**
Bug/issue #, if applicable: 

## Summary

This is a test-only change that improves the flexibility of the `filesIn` integration test-helper in the integration tests.

This PR is in preparation for another change. Whenever I've asked people about how they that I structure my PRs they've said that they prefer multiple smaller single-purpose PRs. I'm trying to do just that with this PR. The purpose of this change is to support writing a new test for a follow up PR that intercepts and customizes the `--output-dir` argument.

## Dependencies

None. 

## Testing

Run `bin/tests`.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] ~Added~ Updated tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] ~Updated documentation if necessary~ Not applicable.

### CODE REVIEW

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Review by anferbui — APPROVED** [review]
LGTM!

**Pull request merged**
