### PR TITLE
Add Clang source module support

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Bug/issue #, if applicable: 

## Summary

https://github.com/Kyle-Ye/swift-docc-plugin-mix-demo#swift-doc-for-objetivec-module

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests
- [ ] Ran the `./bin/test` script and it succeeded
- [ ] Updated documentation if necessary

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
@ethan-kusters  Could you add the PR link you mentioned on the Swift Documentation Workgroup meeting? Thanks

**Comment by Kyle-Ye** [comment]
It works fine to generate Swift symbol-graph for a clang target using the existing SwiftPM API.

Download the following code example and run `swift package --disable-sandbox preview-documentation --target CKit`
[CKit.zip](https://github.com/apple/swift-docc-plugin/files/12071773/CKit.zip)

image

**Comment by d-ronnqvist** [comment]
IIUC this functionality is implemented by https://github.com/swiftlang/swift-docc-plugin/pull/95 instead.

**Comment by Kyle-Ye** [comment]
> IIUC this functionality is implemented by #95 instead.

Thanks for getting this issue resolved! I noticed that my earlier PR addressed a similar fix but hasn't received much attention for a while. I'm curious if there might be any internal processes or factors that influenced the prioritization of this one. Does being an Apple employee play any role in the review process?

Looking forward to understanding more about how things work. Thanks again!

**Comment by Kyle-Ye** [comment]
Also noticed the main difference between #95 and this one is some wording change (e.g change "is not a Swift module" to "is not a Swift/Clang module") and the addition of "any" for the existential module instance.

Curious if these changes warranted a new PR.

Would appreciate any insights. Thanks again!

**Pull request closed without merging**
